In [1]:
import pandas as pd
import mysql.connector
from tabulate import tabulate

# Connected with Database

In [2]:
mydb = mysql.connector.connect(
    host = 'localhost',
    user = 'root',
    password = '243258',
    database = 'DataModel1'
    )
mycursor = mydb.cursor()

# Show all table in database

In [3]:
mycursor.execute('SHOW TABLES')
for i in mycursor:
    print(i)

# Department_Information

## Input and convert

In [4]:
Department_Information = pd.read_csv('Data\Department_Information.csv')

In [5]:
Department_Information.head(5)

  Department_ID                 Department_Name                   DOE
0     IDEPT4670           Aerospace Engineering  1961-05-31T00:00:00Z
1     IDEPT5528  Biosciences and Bioengineering  1943-06-28T00:00:00Z
2     IDEPT3115            Chemical Engineering  1940-05-01T00:00:00Z
3     IDEPT5881                       Chemistry  2013-06-08T00:00:00Z
4     IDEPT4938               Civil Engineering  1941-10-27T00:00:00Z

In [6]:
Department_Information.columns

Index(['Department_ID', 'Department_Name', 'DOE'], dtype='object')

In [7]:
Department_Information.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Department_ID    40 non-null     object
 1   Department_Name  40 non-null     object
 2   DOE              40 non-null     object
dtypes: object(3)
memory usage: 1.1+ KB

In [8]:
Department_Information['DOE'] = pd.to_datetime(Department_Information['DOE'], format='%Y-%m-%d')

In [9]:
Department_Information['DOE'] = Department_Information['DOE'].dt.strftime('%m/%d/%Y')

In [10]:
Department_Information['DOE'] = pd.to_datetime(Department_Information['DOE'], format='%m/%d/%Y')

In [11]:
Department_Information.head(5)

  Department_ID                 Department_Name        DOE
0     IDEPT4670           Aerospace Engineering 1961-05-31
1     IDEPT5528  Biosciences and Bioengineering 1943-06-28
2     IDEPT3115            Chemical Engineering 1940-05-01
3     IDEPT5881                       Chemistry 2013-06-08
4     IDEPT4938               Civil Engineering 1941-10-27

## Create Table

In [12]:
# mycursor.execute('DROP TABLE Department_Information')

In [13]:
mycursor.execute(
    '''CREATE TABLE Department_Information(
        Department_ID varchar(10) UNIQUE,
        Department_Name varchar(100),
        DOE DATE,
        PRIMARY KEY (Department_ID))''')

## Insert values

In [14]:
tb_Department_Information = (
    '''INSERT INTO Department_Information (Department_ID,Department_Name,DOE)
        VALUES (%s,%s,%s)
    ''')

In [15]:
for i,row in Department_Information.iterrows():
    mycursor.execute(tb_Department_Information,list(row))

In [16]:
mycursor.execute('SELECT * FROM Department_Information')
myresult = mycursor.fetchall()
print(tabulate(myresult, headers=['Department_ID', 'Department_Name','DOE' ], tablefmt='psql'))

+-----------------+----------------------------------------------------------------------------+------------+
| Department_ID   | Department_Name                                                            | DOE        |
|-----------------+----------------------------------------------------------------------------+------------|
| IDEPT1096       | School of Management                                                       | 2000-03-07 |
| IDEPT1142       | Centre for Aerospace Systems Design and Engineering (CASDE)                | 1966-07-25 |
| IDEPT1367       | Computer Centre (CC)                                                       | 2001-04-05 |
| IDEPT1378       | Industrial Design Centre                                                   | 1993-02-16 |
| IDEPT1388       | Centre for Policy Studies (CPS)                                            | 1999-01-05 |
| IDEPT1423       | Computer Science & Engineering                                             | 1941-05-03 |
| IDEPT1533       | Centre for Technology Alternatives for Rural Areas (CTARA)                 | 1956-11-14 |
| IDEPT1537       | Humanities & Social Science                                                | 1953-09-14 |
| IDEPT1615       | National Centre for Mathematics (NCM)                                      | 1988-12-08 |
| IDEPT1677       | ABC-EDS Research Academy                                                   | 2002-09-25 |
| IDEPT1825       | Mechanical Engineering                                                     | 1971-09-21 |
| IDEPT1836       | Educational Technology                                                     | 1965-07-04 |
| IDEPT2054       | Electrical Engineering                                                     | 1985-05-27 |
| IDEPT2357       | Energy Science and Engineering                                             | 2007-03-28 |
| IDEPT2425       | Physics                                                                    | 1947-09-14 |
| IDEPT2601       | Centre for Entrepreneurship (DSCE)                                         | 1949-07-10 |
| IDEPT3062       | Centre for Environmental Science and Engineering (CESE)                    | 1973-05-23 |
| IDEPT3115       | Chemical Engineering                                                       | 1940-05-01 |
| IDEPT3778       | Centre for Formal Design and Verification of Software (CFDVS)              | 1958-05-22 |
| IDEPT3868       | Center for Learning and Teaching (PPCCLT)                                  | 1982-03-26 |
| IDEPT4055       | Centre for Urban Science and Engineering (C-USE)                           | 1966-12-25 |
| IDEPT4132       | Earth Sciences                                                             | 1982-08-19 |
| IDEPT4308       | Climate Studies                                                            | 1942-05-26 |
| IDEPT4670       | Aerospace Engineering                                                      | 1961-05-31 |
| IDEPT4938       | Civil Engineering                                                          | 1941-10-27 |
| IDEPT5109       | National Center of Excellence in Technology for Internal Security (NCETIS) | 1956-11-16 |
| IDEPT5127       | Application Software Centre (ASC)                                          | 1951-10-22 |
| IDEPT5408       | Centre for Research in Nanotechnology and Science (CRNTS)                  | 1985-12-26 |
| IDEPT5528       | Biosciences and Bioengineering                                             | 1943-06-28 |
| IDEPT5564       | Systems and Control Engineering                                            | 1981-10-16 |
| IDEPT5881       | Chemistry                                                                  | 2013-06-08 |
| IDEPT6347       | Sophisticated Analytical Instrument Facility (SAIF)                        | 1968-06-17 |
| IDEPT7005       | Centre of Studies in Resources Engineering (CSRE)                          | 1966-08-22 |
| IDEPT7626       | National Centre for Aerospace Innovation and Research (NCAIR)              | 1961-07-18 |
| IDEPT7783       | Centre for Distance Engineering Education Programme (CDEEP)                | 1957-12-10 |
| IDEPT8313       | Metallurgical Engineering & Materials Science                              | 1992-04-14 |
| IDEPT8379       | Mathematics                                                                | 1989-01-03 |
| IDEPT8473       | Centre for Bioengineering (WRCB)                                           | 2001-06-25 |
| IDEPT8598       | Technology and Design (TCTD)                                               | 1941-04-27 |
| IDEPT8825       | Industrial Engineering and Operations Research (IEOR)                      | 1988-11-16 |
+-----------------+----------------------------------------------------------------------------+------------+

# Employee_Information

In [17]:
Employee_Information = pd.read_csv('Data\Employee_Information.csv')

In [18]:
Employee_Information.head(5)

  Employee ID                   DOB                   DOJ Department_ID
0    IU196557  1983-02-23T00:00:00Z  2009-10-31T00:00:00Z     IDEPT4938
1    IU449901  1985-09-02T00:00:00Z  2009-06-07T00:00:00Z     IDEPT2357
2    IU206427  1971-07-30T00:00:00Z  2008-05-09T00:00:00Z     IDEPT4670
3    IU688905  1973-07-20T00:00:00Z  2002-01-17T00:00:00Z     IDEPT2601
4    IU634582  1991-11-16T00:00:00Z  2000-02-13T00:00:00Z     IDEPT7626

In [19]:
Employee_Information.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Employee ID    1000 non-null   object
 1   DOB            1000 non-null   object
 2   DOJ            1000 non-null   object
 3   Department_ID  1000 non-null   object
dtypes: object(4)
memory usage: 31.4+ KB

In [20]:
Employee_Information['DOB'] = pd.to_datetime(Employee_Information['DOB'], format='%Y-%m-%d')
Employee_Information['DOB'] = Employee_Information['DOB'].dt.strftime('%m/%d/%Y')

In [21]:
#Convert dtype = datatime to insert data into table
Employee_Information['DOB'] = pd.to_datetime(Employee_Information['DOB'], format='%m/%d/%Y')

In [22]:
Employee_Information['DOJ'] = pd.to_datetime(Employee_Information['DOJ'], format='%Y-%m-%d')
Employee_Information['DOJ'] = Employee_Information['DOJ'].dt.strftime('%m/%d/%Y')

In [23]:
#Convert dtype = datatime to insert data into table
Employee_Information['DOJ'] = pd.to_datetime(Employee_Information['DOJ'], format='%m/%d/%Y')

In [24]:
Employee_Information.head()

  Employee ID        DOB        DOJ Department_ID
0    IU196557 1983-02-23 2009-10-31     IDEPT4938
1    IU449901 1985-09-02 2009-06-07     IDEPT2357
2    IU206427 1971-07-30 2008-05-09     IDEPT4670
3    IU688905 1973-07-20 2002-01-17     IDEPT2601
4    IU634582 1991-11-16 2000-02-13     IDEPT7626

In [25]:
Employee_Information['Employee ID'].value_counts()

IU444477    2
IU410633    2
IU196557    1
IU932895    1
IU922538    1
           ..
IU826622    1
IU817598    1
IU155569    1
IU390407    1
IU800953    1
Name: Employee ID, Length: 998, dtype: int64

In [26]:
filt = (Employee_Information['Employee ID']== 'IU410633')
Employee_Information.loc[filt]

    Employee ID        DOB        DOJ Department_ID
235    IU410633 1979-05-01 2008-08-14     IDEPT1388
312    IU410633 1973-06-13 2014-05-26     IDEPT6347

## Create Table

In [27]:
# mycursor.execute('DROP TABLE Employee_Information')

In [28]:
mycursor.execute(
    '''CREATE TABLE Employee_Information(
        Employee_ID varchar(10),
        DOB DATE,
        DOJ DATE,
        Department_ID varchar(10),
        FOREIGN KEY (Department_ID) REFERENCES Department_Information(Department_ID))
    ''')

In [29]:
tb_Employee_Information = (
    ''' INSERT INTO Employee_Information(Employee_ID, DOB, DOJ, Department_ID)
        VALUES (%s, %s, %s, %s)
    ''')

In [30]:
for i, row in Employee_Information.iterrows():
    mycursor.execute(tb_Employee_Information,list(row))

In [31]:
mydb.commit()

In [32]:
mycursor.execute('SELECT * FROM Employee_Information')
myresult = mycursor.fetchall()
print(tabulate(myresult, headers=['Employee_ID', 'DOB','DOJ', 'Department_ID' ], tablefmt='psql'))

+---------------+------------+------------+-----------------+
| Employee_ID   | DOB        | DOJ        | Department_ID   |
|---------------+------------+------------+-----------------|
| IU196557      | 1983-02-23 | 2009-10-31 | IDEPT4938       |
| IU449901      | 1985-09-02 | 2009-06-07 | IDEPT2357       |
| IU206427      | 1971-07-30 | 2008-05-09 | IDEPT4670       |
| IU688905      | 1973-07-20 | 2002-01-17 | IDEPT2601       |
| IU634582      | 1991-11-16 | 2000-02-13 | IDEPT7626       |
| IU138624      | 1979-05-18 | 2006-09-27 | IDEPT3778       |
| IU932068      | 1985-07-12 | 2013-05-04 | IDEPT4132       |
| IU572796      | 1978-01-14 | 2008-01-03 | IDEPT1142       |
| IU134670      | 1980-12-15 | 2002-01-15 | IDEPT7626       |
| IU393717      | 1973-04-03 | 2009-08-18 | IDEPT1825       |
| IU175125      | 1985-07-13 | 2001-10-17 | IDEPT1615       |
| IU232618      | 1979-02-12 | 2012-02-03 | IDEPT2601       |
| IU760609      | 1983-04-20 | 2006-01-01 | IDEPT1537       |
| IU508242      | 1988-04-05 | 1999-08-12 | IDEPT5109       |
| IU240338      | 1994-03-21 | 2011-02-16 | IDEPT5881       |
| IU826824      | 1988-05-22 | 2007-09-23 | IDEPT8313       |
| IU544227      | 1990-11-05 | 2008-08-15 | IDEPT5127       |
| IU817422      | 1990-07-07 | 2006-04-17 | IDEPT3778       |
| IU917848      | 1976-08-14 | 2002-08-12 | IDEPT2357       |
| IU635586      | 1991-04-28 | 2004-07-27 | IDEPT6347       |
| IU423398      | 1990-06-24 | 2006-06-09 | IDEPT4938       |
| IU846275      | 1974-09-09 | 2008-08-21 | IDEPT1615       |
| IU509287      | 1975-10-06 | 2009-11-16 | IDEPT1615       |
| IU168857      | 1992-03-22 | 2001-05-10 | IDEPT5109       |
| IU125595      | 1992-09-04 | 2006-07-09 | IDEPT1367       |
| IU423522      | 1977-07-10 | 2006-01-16 | IDEPT5109       |
| IU937233      | 1992-06-18 | 2010-06-21 | IDEPT5881       |
| IU710285      | 1970-10-25 | 2011-04-07 | IDEPT3115       |
| IU951593      | 1991-11-24 | 2007-04-11 | IDEPT6347       |
| IU740065      | 1990-04-20 | 1999-11-22 | IDEPT1423       |
| IU306793      | 1976-12-16 | 2008-02-05 | IDEPT1378       |
| IU364794      | 1994-07-10 | 2012-03-02 | IDEPT7626       |
| IU877470      | 1991-11-10 | 2005-07-31 | IDEPT4938       |
| IU486705      | 1983-02-13 | 2001-09-12 | IDEPT1825       |
| IU511664      | 1987-07-29 | 2006-07-24 | IDEPT1825       |
| IU860113      | 1971-07-26 | 2005-03-20 | IDEPT3062       |
| IU271785      | 1970-01-24 | 2006-04-12 | IDEPT1533       |
| IU357968      | 1974-05-17 | 2012-10-31 | IDEPT5528       |
| IU469799      | 1984-03-29 | 2014-06-22 | IDEPT8313       |
| IU508314      | 1974-03-20 | 2000-03-03 | IDEPT6347       |
| IU940853      | 1983-10-13 | 1999-07-30 | IDEPT2601       |
| IU736890      | 1978-12-25 | 2010-08-27 | IDEPT3778       |
| IU271820      | 1983-06-07 | 2005-09-16 | IDEPT1615       |
| IU861380      | 1985-01-15 | 2000-11-29 | IDEPT1378       |
| IU782822      | 1974-05-05 | 2006-12-01 | IDEPT3778       |
| IU369893      | 1971-05-04 | 2002-06-28 | IDEPT5109       |
| IU430546      | 1993-04-12 | 2011-11-06 | IDEPT2601       |
| IU472467      | 1988-11-13 | 2013-06-20 | IDEPT1378       |
| IU904131      | 1980-09-18 | 2010-04-03 | IDEPT2601       |
| IU201506      | 1986-09-24 | 2006-12-02 | IDEPT5127       |
| IU572132      | 1973-11-07 | 2011-05-14 | IDEPT4055       |
| IU538421      | 1975-03-28 | 2013-03-15 | IDEPT1615       |
| IU353908      | 1987-02-20 | 2005-09-11 | IDEPT2601       |
| IU372096      | 1976-02-23 | 2012-02-03 | IDEPT1615       |
| IU473584      | 1983-04-29 | 2014-06-01 | IDEPT7783       |
| IU754974      | 1976-10-05 | 2010-02-25 | IDEPT5109       |
| IU242634      | 1984-06-20 | 2007-02-23 | IDEPT3868       |
| IU624640      | 1987-10-28 | 2014-07-12 | IDEPT5881       |
| IU987884      | 1971-10-24 | 2004-11-18 | IDEPT2357       |
| IU516465      | 1984-05-15 | 2006-01-06 | IDEPT6347       |
| IU246736      | 1972-12-26 | 2007-02-08 | IDEPT7626       |
| IU454493      | 1988-08-19 | 2002-09-28 | IDEPT1142       |
| IU500587      | 1979-11-30 | 2008-03-13 | IDEPT2425       |
| IU325868      | 1976-06-15 | 2000-05-15 | IDEPT1388       |
| IU616644      | 1973-07-05 | 2007-02-19 | IDEPT1423       |
| IU639998      | 1994-04-20 | 2004-03-09 | IDEPT3115       |
| IU410413      | 1983-11-12 | 2006-02-07 | IDEPT4132       |
| IU114595      | 1986-08-20 | 2001-11-13 | IDEPT4055       |
| IU476789      | 1993-03-12 | 2009-06-16 | IDEPT7783       |
| IU438123      | 1975-01-23 | 2011-02-28 | IDEPT1378       |
| IU183626      | 1975-11-01 | 2006-11-15 | IDEPT5881       |
| IU934207      | 1971-09-08 | 2013-10-04 | IDEPT5127       |
| IU582877      | 1970-07-07 | 2005-10-05 | IDEPT1615       |
| IU815641      | 1990-09-16 | 2010-02-02 | IDEPT1825       |
| IU200937      | 1970-12-15 | 2007-09-26 | IDEPT6347       |
| IU703247      | 1985-10-13 | 2009-08-29 | IDEPT5127       |
| IU184260      | 1970-12-08 | 2004-12-12 | IDEPT4670       |
| IU843331      | 1982-02-13 | 2011-05-28 | IDEPT4938       |
| IU886140      | 1982-08-12 | 2013-01-29 | IDEPT1677       |
| IU760362      | 1980-02-14 | 2006-07-08 | IDEPT1537       |
| IU766698      | 1982-09-07 | 2003-09-21 | IDEPT6347       |
| IU633596      | 1981-01-11 | 2011-08-11 | IDEPT8379       |
| IU133163      | 1989-09-29 | 2009-04-24 | IDEPT5408       |
| IU410918      | 1985-09-08 | 2009-06-09 | IDEPT8598       |
| IU418420      | 1978-05-13 | 2001-01-31 | IDEPT1423       |
| IU996025      | 1991-06-20 | 2008-10-03 | IDEPT1142       |
| IU784101      | 1982-01-26 | 2011-04-27 | IDEPT1537       |
| IU480856      | 1991-06-10 | 2010-06-06 | IDEPT4938       |
| IU507184      | 1986-06-26 | 2012-04-25 | IDEPT7783       |
| IU803872      | 1975-04-11 | 2011-04-28 | IDEPT4132       |
| IU795236      | 1991-12-17 | 2008-05-15 | IDEPT6347       |
| IU632540      | 1981-08-15 | 2009-06-17 | IDEPT1423       |
| IU672641      | 1975-10-23 | 2008-05-17 | IDEPT1537       |
| IU280941      | 1969-08-20 | 2014-05-14 | IDEPT5109       |
| IU573089      | 1976-06-27 | 2001-06-14 | IDEPT1367       |
| IU476100      | 1976-12-13 | 2007-04-09 | IDEPT7626       |
| IU169365      | 1982-02-18 | 2008-07-22 | IDEPT3868       |
| IU333324      | 1986-02-02 | 2000-07-23 | IDEPT7005       |
| IU573623      | 1986-12-12 | 2003-12-04 | IDEPT5528       |
| IU263609      | 1985-01-17 | 1999-12-14 | IDEPT8598       |
| IU799085      | 1977-09-02 | 2014-05-13 | IDEPT2425       |
| IU464114      | 1972-11-30 | 2003-05-27 | IDEPT1378       |
| IU282074      | 1976-08-19 | 2008-08-14 | IDEPT1537       |
| IU300723      | 1985-10-16 | 2001-07-31 | IDEPT4670       |
| IU311031      | 1970-06-04 | 2004-01-20 | IDEPT4132       |
| IU976665      | 1985-11-09 | 2002-04-24 | IDEPT1367       |
| IU796590      | 1992-01-01 | 2012-03-03 | IDEPT5408       |
| IU160380      | 1985-10-06 | 2002-11-17 | IDEPT4938       |
| IU124164      | 1971-06-08 | 2004-08-16 | IDEPT4938       |
| IU293826      | 1982-11-19 | 2007-10-24 | IDEPT1615       |
| IU602414      | 1978-12-18 | 2006-09-04 | IDEPT2601       |
| IU797991      | 1990-10-14 | 2001-09-13 | IDEPT8313       |
| IU718477      | 1994-07-11 | 2005-12-24 | IDEPT3115       |
| IU177035      | 1983-02-13 | 2011-04-30 | IDEPT8379       |
| IU340320      | 1978-11-14 | 2013-12-17 | IDEPT4670       |
| IU603759      | 1979-07-18 | 2004-05-24 | IDEPT1388       |
| IU352216      | 1979-01-27 | 2007-06-18 | IDEPT1825       |
| IU780361      | 1989-10-16 | 2005-07-29 | IDEPT2054       |
| IU595413      | 1990-03-23 | 2012-11-07 | IDEPT5109       |
| IU209624      | 1983-11-05 | 2006-02-17 | IDEPT2425       |
| IU885411      | 1985-01-12 | 2007-06-20 | IDEPT4670       |
| IU238192      | 1991-07-02 | 2008-08-17 | IDEPT7626       |
| IU326182      | 1976-09-14 | 2011-03-18 | IDEPT1423       |
| IU995116      | 1975-06-30 | 1999-10-26 | IDEPT8598       |
| IU976864      | 1973-04-02 | 2002-05-17 | IDEPT4132       |
| IU908955      | 1970-07-22 | 2006-03-24 | IDEPT8313       |
| IU843323      | 1971-09-18 | 2000-02-19 | IDEPT2054       |
| IU870897      | 1978-05-28 | 2004-03-01 | IDEPT5127       |
| IU216190      | 1970-07-11 | 2008-11-03 | IDEPT3062       |
| IU960771      | 1983-02-17 | 2002-06-16 | IDEPT7626       |
| IU167781      | 1989-11-17 | 2014-04-01 | IDEPT8313       |
| IU748850      | 1980-02-19 | 1999-12-22 | IDEPT1378       |
| IU680743      | 1973-11-08 | 2006-06-08 | IDEPT4938       |
| IU348664      | 1969-08-30 | 2002-02-01 | IDEPT6347       |
| IU300148      | 1990-11-26 | 2001-01-14 | IDEPT1142       |
| IU968470      | 1983-07-27 | 2010-10-06 | IDEPT6347       |
| IU338809      | 1991-06-30 | 2004-04-22 | IDEPT1533       |
| IU119855      | 1974-02-16 | 2013-07-05 | IDEPT5109       |
| IU171535      | 1972-11-23 | 2013-10-13 | IDEPT1677       |
| IU428631      | 1987-11-27 | 2001-06-02 | IDEPT1825       |
| IU674290      | 1983-07-24 | 2006-03-29 | IDEPT1367       |
| IU580499      | 1981-12-08 | 2011-01-29 | IDEPT2054       |
| IU486342      | 1994-05-13 | 2008-10-11 | IDEPT7626       |
| IU820511      | 1984-12-24 | 2010-11-11 | IDEPT1367       |
| IU407408      | 1973-01-31 | 2006-10-19 | IDEPT4132       |
| IU171891      | 1971-04-15 | 2003-07-18 | IDEPT3115       |
| IU275641      | 1978-01-01 | 2014-01-15 | IDEPT4055       |
| IU780299      | 1988-12-05 | 2007-10-03 | IDEPT4938       |
| IU300673      | 1984-05-15 | 2001-03-28 | IDEPT5528       |
| IU301330      | 1980-11-30 | 2001-08-05 | IDEPT2357       |
| IU564831      | 1981-08-27 | 2006-05-15 | IDEPT1388       |
| IU391736      | 1988-01-19 | 2007-09-02 | IDEPT5127       |
| IU133525      | 1978-09-01 | 2010-08-26 | IDEPT2357       |
| IU160119      | 1979-07-16 | 2003-04-27 | IDEPT4132       |
| IU806621      | 1983-01-25 | 2009-07-29 | IDEPT1142       |
| IU908741      | 1986-07-07 | 2013-11-23 | IDEPT1677       |
| IU821348      | 1980-04-28 | 2010-04-13 | IDEPT1537       |
| IU271286      | 1971-06-18 | 2007-05-30 | IDEPT3868       |
| IU859028      | 1985-11-09 | 2009-12-22 | IDEPT1367       |
| IU440953      | 1991-02-10 | 2012-08-21 | IDEPT8313       |
| IU782253      | 1988-07-30 | 2011-06-03 | IDEPT2054       |
| IU641916      | 1980-01-25 | 2008-02-23 | IDEPT7005       |
| IU705753      | 1985-05-12 | 2001-02-20 | IDEPT1367       |
| IU753520      | 1972-12-05 | 2006-10-04 | IDEPT3062       |
| IU829108      | 1976-01-12 | 2007-05-11 | IDEPT6347       |
| IU138448      | 1970-04-12 | 2003-03-10 | IDEPT8313       |
| IU420763      | 1974-02-06 | 2008-05-27 | IDEPT7626       |
| IU233038      | 1992-10-02 | 2008-12-12 | IDEPT5528       |
| IU695482      | 1977-12-11 | 2008-04-18 | IDEPT4938       |
| IU528881      | 1992-12-13 | 2011-03-27 | IDEPT5127       |
| IU780387      | 1977-12-26 | 2006-02-13 | IDEPT7783       |
| IU758744      | 1991-04-20 | 2000-06-24 | IDEPT5528       |
| IU614210      | 1979-06-01 | 2001-09-02 | IDEPT4670       |
| IU570506      | 1970-09-11 | 2005-10-09 | IDEPT4670       |
| IU277655      | 1988-06-04 | 2001-09-18 | IDEPT5408       |
| IU677053      | 1992-02-01 | 2003-05-27 | IDEPT5408       |
| IU661044      | 1989-07-18 | 2010-04-08 | IDEPT7626       |
| IU739520      | 1976-05-16 | 2001-05-25 | IDEPT5881       |
| IU445489      | 1988-10-01 | 2006-01-24 | IDEPT5127       |
| IU838077      | 1993-07-18 | 2007-04-12 | IDEPT1825       |
| IU164953      | 1991-06-30 | 2007-07-26 | IDEPT3868       |
| IU605579      | 1973-07-29 | 2007-08-13 | IDEPT1677       |
| IU202628      | 1981-06-11 | 2007-05-19 | IDEPT8379       |
| IU469763      | 1984-12-17 | 2010-04-07 | IDEPT1142       |
| IU429696      | 1993-12-03 | 2001-01-12 | IDEPT5127       |
| IU702617      | 1969-09-30 | 2008-04-01 | IDEPT6347       |
| IU301679      | 1986-10-04 | 2014-01-01 | IDEPT1388       |
| IU136186      | 1984-11-03 | 2014-07-11 | IDEPT1142       |
| IU226782      | 1978-11-07 | 2013-09-09 | IDEPT1533       |
| IU469798      | 1983-06-13 | 2008-08-27 | IDEPT5109       |
| IU731281      | 1976-01-26 | 2007-07-02 | IDEPT5408       |
| IU573049      | 1994-05-08 | 2000-03-01 | IDEPT3115       |
| IU845710      | 1972-05-09 | 2001-10-26 | IDEPT5109       |
| IU228243      | 1971-03-13 | 2003-09-28 | IDEPT1615       |
| IU684059      | 1974-11-03 | 2000-03-12 | IDEPT6347       |
| IU869693      | 1972-12-26 | 2010-01-13 | IDEPT2054       |
| IU418731      | 1983-01-10 | 2014-04-13 | IDEPT1825       |
| IU397409      | 1980-10-29 | 2006-08-24 | IDEPT7783       |
| IU892420      | 1969-08-11 | 2001-08-04 | IDEPT7783       |
| IU122721      | 1990-01-21 | 2005-08-30 | IDEPT2601       |
| IU512644      | 1989-07-22 | 2009-08-01 | IDEPT4132       |
| IU909240      | 1982-01-31 | 2014-05-09 | IDEPT3115       |
| IU663263      | 1980-12-30 | 2004-02-05 | IDEPT5109       |
| IU425212      | 1976-01-22 | 2012-12-10 | IDEPT4670       |
| IU202625      | 1976-11-27 | 2011-11-14 | IDEPT1533       |
| IU738148      | 1993-01-20 | 2013-12-13 | IDEPT1388       |
| IU430177      | 1984-12-31 | 2007-10-20 | IDEPT4670       |
| IU635288      | 1970-03-13 | 2012-06-05 | IDEPT3115       |
| IU789680      | 1981-12-25 | 2010-07-09 | IDEPT3062       |
| IU182243      | 1992-01-21 | 2008-11-09 | IDEPT8313       |
| IU327985      | 1983-07-06 | 2009-08-24 | IDEPT4132       |
| IU533528      | 1985-05-20 | 2005-03-03 | IDEPT3115       |
| IU723031      | 1981-06-06 | 2006-07-20 | IDEPT8379       |
| IU934910      | 1986-01-08 | 2009-06-04 | IDEPT1537       |
| IU169952      | 1990-10-25 | 2004-03-11 | IDEPT5408       |
| IU178366      | 1991-10-25 | 2004-11-01 | IDEPT3062       |
| IU721549      | 1991-06-19 | 2009-12-02 | IDEPT1142       |
| IU516266      | 1977-09-03 | 2004-12-06 | IDEPT4670       |
| IU862692      | 1989-02-24 | 2012-10-16 | IDEPT1825       |
| IU207880      | 1990-10-22 | 2012-11-25 | IDEPT5109       |
| IU820075      | 1970-09-29 | 2013-11-03 | IDEPT8379       |
| IU427979      | 1984-10-04 | 2012-06-12 | IDEPT3062       |
| IU325411      | 1986-10-30 | 2009-03-01 | IDEPT1677       |
| IU559192      | 1980-06-06 | 2009-01-19 | IDEPT4670       |
| IU642949      | 1989-09-02 | 2012-04-24 | IDEPT1537       |
| IU341933      | 1990-07-11 | 2012-08-01 | IDEPT7005       |
| IU906322      | 1976-10-18 | 2001-01-21 | IDEPT4670       |
| IU816890      | 1979-06-21 | 1999-08-09 | IDEPT4938       |
| IU506955      | 1972-10-14 | 2006-05-19 | IDEPT8598       |
| IU211110      | 1983-04-04 | 2012-08-01 | IDEPT2601       |
| IU408398      | 1987-01-30 | 2001-07-25 | IDEPT1825       |
| IU751501      | 1983-12-14 | 2002-06-28 | IDEPT4055       |
| IU170799      | 1974-03-01 | 2005-03-12 | IDEPT6347       |
| IU752831      | 1989-01-21 | 2005-12-12 | IDEPT7783       |
| IU850341      | 1989-08-03 | 2001-01-24 | IDEPT7626       |
| IU410633      | 1979-05-01 | 2008-08-14 | IDEPT1388       |
| IU864193      | 1993-01-30 | 2013-11-12 | IDEPT6347       |
| IU681338      | 1975-12-12 | 2009-03-07 | IDEPT2601       |
| IU265455      | 1982-10-25 | 2001-02-04 | IDEPT8598       |
| IU375598      | 1989-05-22 | 2000-10-21 | IDEPT3778       |
| IU508574      | 1970-11-20 | 2009-10-10 | IDEPT2601       |
| IU960495      | 1988-06-19 | 2003-08-30 | IDEPT1537       |
| IU428752      | 1974-06-24 | 2007-06-09 | IDEPT3868       |
| IU204067      | 1979-05-02 | 2006-07-07 | IDEPT3062       |
| IU208561      | 1988-10-26 | 2011-01-31 | IDEPT8379       |
| IU519293      | 1984-09-15 | 2009-06-04 | IDEPT3062       |
| IU822516      | 1978-07-09 | 2014-05-25 | IDEPT5881       |
| IU995320      | 1977-03-05 | 2003-07-17 | IDEPT1825       |
| IU964518      | 1981-06-23 | 2013-08-23 | IDEPT5881       |
| IU894235      | 1973-11-12 | 2012-08-26 | IDEPT1615       |
| IU288401      | 1977-03-18 | 1999-09-08 | IDEPT3868       |
| IU291748      | 1989-12-15 | 2001-07-29 | IDEPT5881       |
| IU241381      | 1994-07-13 | 2011-11-16 | IDEPT1142       |
| IU268506      | 1982-07-16 | 2007-02-19 | IDEPT8598       |
| IU366991      | 1991-09-05 | 2002-10-12 | IDEPT5528       |
| IU399810      | 1976-09-28 | 2009-01-29 | IDEPT8313       |
| IU312327      | 1975-04-24 | 2012-03-17 | IDEPT3778       |
| IU153231      | 1969-10-24 | 2007-11-27 | IDEPT3115       |
| IU657927      | 1982-12-11 | 2001-05-03 | IDEPT2425       |
| IU191586      | 1978-09-18 | 2002-04-23 | IDEPT7626       |
| IU246186      | 1986-11-02 | 2009-01-19 | IDEPT2054       |
| IU981891      | 1977-04-27 | 2009-03-10 | IDEPT1378       |
| IU538991      | 1994-04-06 | 2014-03-20 | IDEPT5109       |
| IU268651      | 1971-11-23 | 2002-10-26 | IDEPT3778       |
| IU738373      | 1978-03-05 | 2005-01-14 | IDEPT5127       |
| IU944782      | 1980-08-31 | 2007-08-27 | IDEPT3115       |
| IU626787      | 1977-11-05 | 2010-08-05 | IDEPT2601       |
| IU214283      | 1980-02-24 | 2008-12-27 | IDEPT2425       |
| IU510307      | 1988-09-03 | 2011-01-25 | IDEPT3778       |
| IU761906      | 1976-12-11 | 2013-04-10 | IDEPT5109       |
| IU390465      | 1989-08-04 | 2001-05-13 | IDEPT3778       |
| IU490542      | 1984-03-31 | 2005-01-30 | IDEPT8379       |
| IU349204      | 1981-12-22 | 2009-09-27 | IDEPT4938       |
| IU323581      | 1987-02-18 | 2008-09-27 | IDEPT3115       |
| IU217492      | 1970-05-08 | 2003-11-20 | IDEPT2601       |
| IU220175      | 1990-04-03 | 2002-01-10 | IDEPT7783       |
| IU821623      | 1977-05-31 | 2007-01-01 | IDEPT7626       |
| IU870155      | 1989-09-14 | 2008-10-31 | IDEPT1388       |
| IU480250      | 1988-05-27 | 2010-01-27 | IDEPT1388       |
| IU819549      | 1989-06-11 | 2007-03-27 | IDEPT1533       |
| IU187772      | 1983-07-29 | 2013-05-11 | IDEPT7626       |
| IU498408      | 1992-09-30 | 2005-08-20 | IDEPT1677       |
| IU124080      | 1976-02-21 | 2003-10-31 | IDEPT1677       |
| IU260788      | 1979-05-10 | 2007-11-19 | IDEPT1615       |
| IU366351      | 1976-11-12 | 2003-10-16 | IDEPT1423       |
| IU492187      | 1989-12-25 | 2014-07-04 | IDEPT1142       |
| IU222599      | 1969-09-18 | 2013-08-19 | IDEPT3115       |
| IU415304      | 1975-03-27 | 2013-11-23 | IDEPT2425       |
| IU947736      | 1988-11-08 | 2008-11-24 | IDEPT2425       |
| IU906894      | 1975-09-15 | 2010-12-19 | IDEPT3115       |
| IU973524      | 1983-04-04 | 2011-02-08 | IDEPT1388       |
| IU327964      | 1975-10-29 | 2000-08-05 | IDEPT7783       |
| IU370459      | 1990-08-03 | 2006-04-22 | IDEPT3778       |
| IU444477      | 1979-04-30 | 2005-03-30 | IDEPT4132       |
| IU571216      | 1976-02-22 | 2007-10-11 | IDEPT1388       |
| IU630070      | 1985-03-13 | 2000-04-27 | IDEPT4670       |
| IU317969      | 1986-09-26 | 2000-05-25 | IDEPT1537       |
| IU342775      | 1993-06-18 | 2011-06-23 | IDEPT2601       |
| IU348500      | 1973-10-10 | 2013-08-31 | IDEPT4938       |
| IU971602      | 1975-11-10 | 2013-05-24 | IDEPT4132       |
| IU610008      | 1973-05-16 | 2009-04-23 | IDEPT4132       |
| IU976032      | 1979-07-13 | 2006-09-15 | IDEPT3868       |
| IU879530      | 1986-04-28 | 2004-01-11 | IDEPT5109       |
| IU777655      | 1978-06-11 | 2008-10-12 | IDEPT2357       |
| IU146516      | 1987-01-29 | 2010-03-06 | IDEPT1677       |
| IU588644      | 1972-02-08 | 2002-05-26 | IDEPT1615       |
| IU131301      | 1987-10-08 | 2010-05-24 | IDEPT5109       |
| IU330011      | 1973-02-24 | 2002-05-16 | IDEPT8379       |
| IU437832      | 1972-05-04 | 2002-05-06 | IDEPT7005       |
| IU603458      | 1973-08-26 | 2004-05-30 | IDEPT1367       |
| IU290072      | 1987-04-14 | 2012-03-20 | IDEPT4132       |
| IU674734      | 1987-12-20 | 2002-12-22 | IDEPT2357       |
| IU410633      | 1973-06-13 | 2014-05-26 | IDEPT6347       |
| IU923599      | 1990-05-22 | 2011-12-27 | IDEPT1142       |
| IU263351      | 1978-12-20 | 2009-04-21 | IDEPT3778       |
| IU677544      | 1984-02-11 | 2000-05-15 | IDEPT1537       |
| IU304996      | 1987-12-25 | 2008-07-13 | IDEPT5127       |
| IU689925      | 1975-02-13 | 2007-10-04 | IDEPT2357       |
| IU250243      | 1987-06-29 | 2004-02-26 | IDEPT5408       |

# Student_Counceling_Information

In [33]:
Student_Counceling_Information = pd.read_csv('Data\Student_Counceling_Information.csv')

In [34]:
Student_Counceling_Information.head(5)

,Student_ID,DOA,DOB,Department_Choices,Department_Admission
0,SID20131143,2013-07-01T00:00:00Z,1996-02-05T00:00:00Z,IDEPT7783,IDEPT7783
1,SID20131151,2013-07-01T00:00:00Z,1995-07-31T00:00:00Z,IDEPT6347,IDEPT6347
2,SID20131171,2013-07-01T00:00:00Z,1995-09-05T00:00:00Z,IDEPT1836,IDEPT1836
3,SID20131176,2013-07-01T00:00:00Z,1996-01-12T00:00:00Z,IDEPT8473,IDEPT8473
4,SID20131177,2013-07-01T00:00:00Z,1995-07-30T00:00:00Z,IDEPT5528,IDEPT5528

In [35]:
Student_Counceling_Information['DOA'] = pd.to_datetime(Student_Counceling_Information['DOA'], format='%Y-%m-%d')
Student_Counceling_Information['DOA'] = Student_Counceling_Information['DOA'].dt.strftime('%m/%d/%Y')

In [36]:
#Convert dtype = datatime to insert data into table
Student_Counceling_Information['DOA'] = pd.to_datetime(Student_Counceling_Information['DOA'], format='%m/%d/%Y')

In [37]:
Student_Counceling_Information['DOB'] = pd.to_datetime(Student_Counceling_Information['DOB'], format='%Y-%m-%d')
Student_Counceling_Information['DOB'] = Student_Counceling_Information['DOB'].dt.strftime('%m/%d/%Y')

In [38]:
#Convert dtype = datatime to insert data into table
Student_Counceling_Information['DOB'] = pd.to_datetime(Student_Counceling_Information['DOB'], format='%m/%d/%Y')

In [39]:
Student_Counceling_Information.head(5)

    Student_ID        DOA        DOB Department_Choices Department_Admission
0  SID20131143 2013-07-01 1996-02-05          IDEPT7783            IDEPT7783
1  SID20131151 2013-07-01 1995-07-31          IDEPT6347            IDEPT6347
2  SID20131171 2013-07-01 1995-09-05          IDEPT1836            IDEPT1836
3  SID20131176 2013-07-01 1996-01-12          IDEPT8473            IDEPT8473
4  SID20131177 2013-07-01 1995-07-30          IDEPT5528            IDEPT5528

In [40]:
Student_Counceling_Information['Student_ID'].value_counts()

SID20162976    3
SID20166532    3
SID20184391    3
SID20168634    3
SID20176283    3
              ..
SID20151584    1
SID20151594    1
SID20151616    1
SID20151623    1
SID20189989    1
Name: Student_ID, Length: 3819, dtype: int64

## Create table

In [41]:
mycursor.execute(
    '''CREATE TABLE Student_Counceling_Information(
        Student_ID varchar(20),
        DOA DATE,
        DOB DATE,
        Department_Choices varchar(10),
        Department_Admission varchar(10),
        FOREIGN KEY (Department_Choices) REFERENCES Department_Information(Department_ID),
        FOREIGN KEY (Department_Admission) REFERENCES Department_Information(Department_ID))
    ''')

## Insert Values

In [42]:
tb_Student_Counceling_Information =(
    '''INSERT INTO Student_Counceling_Information(Student_ID, DOA, DOB, Department_Choices, Department_Admission)
        VALUES (%s, %s, %s, %s, %s)
    ''')

In [43]:
for i, row in Student_Counceling_Information.iterrows():
    mycursor.execute(tb_Student_Counceling_Information,list(row))
mydb.commit()

In [44]:
mycursor.execute('SELECT * FROM Student_Counceling_Information LIMIT 5')
myresult = mycursor.fetchall()
print(tabulate(myresult, headers=['Student_ID', 'DOA', 'DOB', 'Department_Choices', 'Department_Admission'],tablefmt='psql'))

+--------------+------------+------------+----------------------+------------------------+
| Student_ID   | DOA        | DOB        | Department_Choices   | Department_Admission   |
|--------------+------------+------------+----------------------+------------------------|
| SID20131143  | 2013-07-01 | 1996-02-05 | IDEPT7783            | IDEPT7783              |
| SID20131151  | 2013-07-01 | 1995-07-31 | IDEPT6347            | IDEPT6347              |
| SID20131171  | 2013-07-01 | 1995-09-05 | IDEPT1836            | IDEPT1836              |
| SID20131176  | 2013-07-01 | 1996-01-12 | IDEPT8473            | IDEPT8473              |
| SID20131177  | 2013-07-01 | 1995-07-30 | IDEPT5528            | IDEPT5528              |
+--------------+------------+------------+----------------------+------------------------+

# Student_Performance_Data

In [45]:
Student_Performance_Data = pd.read_csv('Data\Student_Performance_Data.csv')

In [46]:
Student_Performance_Data.head(5)

    Student_ID Semster_Name     Paper_ID Paper_Name  Marks
0  SID20131143        Sem_1  SEMI0012995    Paper 1     44
1  SID20131143        Sem_1  SEMI0015183    Paper 2     74
2  SID20131143        Sem_1  SEMI0018371    Paper 3     80
3  SID20131143        Sem_1  SEMI0015910    Paper 4     44
4  SID20131143        Sem_1  SEMI0016208    Paper 5     95

In [47]:
Student_Performance_Data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 209611 entries, 0 to 209610
Data columns (total 5 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   Student_ID    209611 non-null  object
 1   Semster_Name  209611 non-null  object
 2   Paper_ID      209611 non-null  object
 3   Paper_Name    209611 non-null  object
 4   Marks         209611 non-null  int64
dtypes: int64(1), object(4)
memory usage: 8.0+ MB

## Create table

In [48]:
mycursor.execute(
    '''CREATE TABLE Student_Performance_Data(
        Student_ID varchar(20),
        Semster_Name varchar(10),
        Paper_ID varchar (20),
        Paper_Name varchar(10),
        Marks int
        )
    ''')

## Insert Values

In [49]:
tb_Student_Performance_Data = (
    '''INSERT INTO Student_Performance_Data(Student_ID,Semster_Name,Paper_ID,Paper_Name,Marks)
        VALUES (%s, %s, %s, %s, %s)
    ''')

In [50]:
for i, row in Student_Performance_Data.iterrows():
    mycursor.execute(tb_Student_Performance_Data,list(row))
mydb.commit()

In [51]:
mycursor.execute('SELECT * FROM Student_Performance_Data LIMIT 5')
myresult = mycursor.fetchall()
print(tabulate(myresult, headers = ['Student_ID','Semster_Name','Paper_ID','Paper_Name','Marks'], tablefmt = 'psql'))

+--------------+----------------+-------------+--------------+---------+
| Student_ID   | Semster_Name   | Paper_ID    | Paper_Name   |   Marks |
|--------------+----------------+-------------+--------------+---------|
| SID20131143  | Sem_1          | SEMI0012995 | Paper 1      |      44 |
| SID20131143  | Sem_1          | SEMI0015183 | Paper 2      |      74 |
| SID20131143  | Sem_1          | SEMI0018371 | Paper 3      |      80 |
| SID20131143  | Sem_1          | SEMI0015910 | Paper 4      |      44 |
| SID20131143  | Sem_1          | SEMI0016208 | Paper 5      |      95 |
+--------------+----------------+-------------+--------------+---------+